---

- hosts: all
  connection: local
  gather_facts: no
  roles:
  - role: Juniper.junos
  tasks:
  - name: static pw
    set_fact:
      username: ansible
      password: testing123

  - name: Get TimeDateStamp
    set_fact:
      mydate: "{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
  - name: Set Facts
    set_fact:
      single_re_script: "single.slax"
      dual_re_script: "dual.slax"
      junos_conf: "./event.set"
      build_path_pre: "build/{{ inventory_hostname }}/{{ mydate}}"

  - name: Create subdirectory for storing configs and diffs
    file:
      path: "{{ build_path_pre }}"
      state: directory
      mode: 0770

  - name: Junos NEW Get Facts
    juniper_junos_facts:
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      user: "{{ username }}"
      passwd: "{{password|default()}}"
    register: facts

  - name: Select appropriate SLAX script
    set_fact:
      script: "{% if facts.ansible_facts.junos['has_2RE']%}{{ dual_re_script }}{% else%}{{ single_re_script }}{% endif %}"

  - name: Test scp with expect
    expect:
      command: scp {{ script }} {{ username }}@{{ inventory_hostname }}:/var/db/scripts/event/
      responses:
        "(yes/no)":
          - "yes"
        "Password":
          - "{{ password }}"

  - name: Build config snippet from template
    template:
      src: "event.j2"
      dest: "{{ junos_conf }}"

  - name: pushing config (Dry Run with show|compare)
    juniper_junos_config:
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      user: "{{ username }}"
      passwd: "{{ password|default() }}"
      load: set
      src: "{{ junos_conf }}"
      dest_dir: "{{ build_path_pre }}"
      diff: true
      check: true
      commit: false
      port: 22
      timeout: 60
    register: juniper_junos_config_result

  - name: proceed with config changes if needed
    import_tasks: commit_confirmed_tasks.yml
    when: juniper_junos_config_result|changed
